/**
 * Emit docs/PORTFOLIO.md — the account statement in full.
 *
 * Generated rather than written by hand: every figure below is replayed from
 * src/data/ledger.ts through the same engine the app uses, so the document
 * cannot drift from the ledger. Re-run it whenever a trade or a mark changes.
 *
 *   npm run statement
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { INCEPTION_DATE, INITIAL_CAPITAL, TRADES, ACCOUNT } from '../src/data/ledger';
import { SNAPSHOT, SNAPSHOT_AS_OF } from '../src/data/snapshot';
import { instrumentFor } from '../src/data/instruments';
import { buildPortfolio, replayLedger, checkInvariants } from '../src/lib/portfolio';

const out = process.argv[2] ?? fileURLToPath(new URL('../docs/PORTFOLIO.md', import.meta.url));

const usd = (n: number, dp = 2) =>
  `${n < 0 ? '-' : ''}$${Math.abs(n).toLocaleString('en-US', {
    minimumFractionDigits: dp,
    maximumFractionDigits: dp,
  })}`;
const signed = (n: number) => `${n >= 0 ? '+' : '-'}$${Math.abs(n).toLocaleString('en-US', {
  minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const pct = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(2)}%`;
const qty = (n: number) => n.toLocaleString('en-US');
const px = (n: number, dp = 2) => n.toFixed(dp);
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const day = (iso: string) => {
  const [y, m, d] = iso.slice(0, 10).split('-');
  return `${d} ${MONTHS[Number(m) - 1]} ${y}`;
};

const quotes = Object.fromEntries(
  Object.entries(SNAPSHOT).map(([s, q]) => [s, { price: q.price, previousClose: q.previousClose }]),
);
const asOf = new Date(SNAPSHOT_AS_OF);
const portfolio = buildPortfolio(quotes, { asOf });
const { positions, summary } = portfolio;
const replay = replayLedger();

/* --- the ledger, with a running cash balance -------------------------------- */
const ordered = [...TRADES].sort((a, b) =>
  a.date === b.date ? a.id.localeCompare(b.id) : a.date.localeCompare(b.date),
);

// Average cost at the moment of each sale, so the realised figure can be shown
// as the arithmetic that produced it rather than asserted.
const running = new Map<string, { qty: number; basis: number }>();
const realisedRows: string[] = [];
let cash = INITIAL_CAPITAL;

const ledgerRows = ordered.map((t) => {
  const held = running.get(t.symbol) ?? { qty: 0, basis: 0 };
  const gross = t.quantity * t.price;
  if (t.side === 'BUY') {
    cash -= gross;
    running.set(t.symbol, { qty: held.qty + t.quantity, basis: held.basis + gross });
  } else {
    const avg = held.qty > 0 ? held.basis / held.qty : 0;
    const relieved = avg * t.quantity;
    cash += gross;
    running.set(t.symbol, { qty: held.qty - t.quantity, basis: held.basis - relieved });
    realisedRows.push(
      `| ${t.id} | ${day(t.date)} | ${t.symbol} | ${qty(t.quantity)} | ${px(avg, 4)} | ` +
      `${px(t.price)} | ${usd(relieved)} | ${usd(gross)} | **${signed(gross - relieved)}** |`,
    );
  }
  return (
    `| ${t.id} | ${day(t.date)} | ${t.side} | ${t.symbol} | ${qty(t.quantity)} | ` +
    `${px(t.price)} | ${t.side === 'BUY' ? usd(-gross) : signed(gross)} | ` +
    `${usd(cash)} |`
  );
});

const noteRows = ordered.map((t) => `| ${t.id} | ${t.side} ${qty(t.quantity)} ${t.symbol} | ${t.note} |`);

const holdingRows = positions.map((p) => {
  const i = instrumentFor(p.symbol);
  return (
    `| ${p.symbol} | ${i.name} | ${i.sector} | ${qty(p.quantity)} | ${px(p.averageCost, 4)} | ` +
    `${px(p.price)} | ${usd(p.costBasis)} | ${usd(p.marketValue)} | ${signed(p.unrealizedPnl)} | ` +
    `${pct(p.unrealizedPct)} | ${(p.weight * 100).toFixed(2)}% |`
  );
});

const totalCost = positions.reduce((s, p) => s + p.costBasis, 0);
const invariants = checkInvariants(portfolio);
const failing = invariants.filter((i) => !i.passed);

const md = `# Account statement

Account **${ACCOUNT.id}** · ${ACCOUNT.title} · ${ACCOUNT.baseCurrency}
Mandate: ${ACCOUNT.strategy}
Opened **${day(INCEPTION_DATE)}** with a single deposit of **${usd(INITIAL_CAPITAL)}**. No money
has been added or withdrawn since.

Marks as of **${day(SNAPSHOT_AS_OF)}** (the offline snapshot the app falls back to; when the
device has a network the same ledger is revalued against live quotes and every
figure below moves with the market).

> This document is generated by \`npm run statement\` from \`src/data/ledger.ts\`.
> Nothing here is stored — positions, cost basis, realised P&L, cash and the
> headline return are all replayed from the ${TRADES.length} transactions each time.

---

## 1. Summary

| | |
|---|---:|
| Deposit | ${usd(summary.initialCapital)} |
| Securities at market | ${usd(summary.securitiesValue)} |
| Settled cash | ${usd(summary.cash)} |
| **Net liquidation value** | **${usd(summary.netLiquidation)}** |
| Cost basis of open positions | ${usd(summary.openCostBasis)} |
| Unrealised P&L | ${signed(summary.unrealizedPnl)} |
| Realised P&L | ${signed(summary.realizedPnl)} |
| **Total P&L** | **${signed(summary.totalPnl)}** |
| **Total return** | **${pct(summary.totalReturnPct)}** |
| Growth on the deposit | ${summary.growth.toFixed(2)}x |
| Holding period | ${summary.yearsHeld.toFixed(2)} years |
| CAGR | ${pct(summary.cagrPct)} |
| Day P&L | ${signed(summary.dayPnl)} (${pct(summary.dayPnlPct)}) |
| Positions | ${positions.length} — ${summary.winners} up, ${summary.losers} down |

---

## 2. The ledger

Every fill, in order, with the settled cash balance after each one. Prices are
split-adjusted execution prices; commission is zero.

| # | Date | Side | Symbol | Qty | Price | Cash effect | Cash after |
|---|---|---|---|---:|---:|---:|---:|
${ledgerRows.join('\n')}

Cash never goes negative: the lowest balance over the whole history is
**${usd(replay.minimumCash)}**, and it ends at **${usd(replay.cash)}**.

### Why each trade was done

| # | Trade | Note |
|---|---|---|
${noteRows.join('\n')}

---

## 3. Sales and realised P&L

Two sales, both partial. Cost is relieved at **average cost**, the US broker
default — so a sale takes basis out at the line's blended average, not at the
price of any particular lot.

| # | Date | Symbol | Qty sold | Avg cost at sale | Sale price | Basis relieved | Proceeds | Realised |
|---|---|---|---:|---:|---:|---:|---:|---:|
${realisedRows.join('\n')}

Total realised: **${signed(replay.realizedPnl)}**.

Both sales are why the account's return is not simply the weighted return of
what it holds today: the proceeds were recycled into positions bought later.
The NVDA trim funded the AI-cloud names; the MU top-slice funded PYPL.

---

## 4. Open positions

Sorted by market value. Average cost is the remaining basis divided by the
remaining shares — for NVDA and MU that is the basis left after the sales above,
which under average cost is unchanged per share.

| Symbol | Name | Sector | Qty | Avg cost | Last | Cost basis | Market value | Unrealised | Return | Weight |
|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|
${holdingRows.join('\n')}
| — | USD cash | — | — | — | — | — | ${usd(summary.cash)} | — | — | ${((summary.cash / summary.netLiquidation) * 100).toFixed(2)}% |
| | | | | | | **${usd(totalCost)}** | **${usd(summary.netLiquidation)}** | **${signed(summary.unrealizedPnl)}** | | **100.00%** |

Weights are a share of net liquidation value, so cash is in the denominator and
the position weights sum to just under 100%.

---

## 5. How the figures tie out

${invariants.map((i) => `- **${i.name}** — ${i.passed ? 'holds' : 'FAILS'} at ${i.expected.toFixed(2)}. ${i.detail}`).join('\n')}

${failing.length === 0
  ? `All ${invariants.length} identities hold. \`npm run audit\` re-checks them, plus the ledger
constraints (chronological order, unique ids, whole shares, one external cash
movement, no negative cash, no overselling) and the mandate constraints.`
  : `**${failing.length} identity does not hold — the ledger needs attention.**`}

The chain in words: ${usd(INITIAL_CAPITAL)} in, ${usd(INITIAL_CAPITAL - replay.cash)} of it spent net on
stock, leaving ${usd(replay.cash)} of cash. The stock bought is carried at
${usd(summary.openCostBasis)} of basis and marks at ${usd(summary.securitiesValue)}, a gain of
${signed(summary.unrealizedPnl)}. Add ${signed(replay.realizedPnl)} banked on the two sales and the
account is worth ${usd(summary.netLiquidation)} — ${pct(summary.totalReturnPct)} on the deposit,
${summary.growth.toFixed(2)}x over ${summary.yearsHeld.toFixed(2)} years.
`;

writeFileSync(out, md);
console.log(`statement -> ${out}  (${(md.length / 1024).toFixed(1)} KB, ${TRADES.length} trades, ${positions.length} positions)`);
if (failing.length) process.exit(1);
